version: '3.9'

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    command: >
      sh -c "
      python manage.py wait_for_database &&
      python manage.py migrate --no-input &&
      python manage.py init_stage &&
      python manage.py collectstatic --no-input &&
      python manage.py create_default_superuser &&
      gunicorn triproverochki.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - ./:/home/app/backend/
      - static_volume:/home/app/backend/static/
    env_file:
      - ./.env
    depends_on:
      - redis

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8023:8023"
#      - "443:443"
    volumes:
      - static_volume:/home/app/backend/static/
    depends_on:
      - backend

  celery-worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/home/app/backend/
    depends_on:
      - redis
      - backend
    command: celery --app=triproverochki --workdir=/home/app/backend worker --loglevel=info

volumes:
  postgres_data:
  static_volume:
