# Generated by Django 4.0.5 on 2022-07-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Тексты'},
        ),
    ]
