# Generated by Django 4.0.5 on 2022-07-08 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayFormURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True, unique=True, verbose_name='Ссылка на форму')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_form_urls', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('week_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_form_urls', to='api.weekid', verbose_name='Номер недели')),
            ],
            options={
                'verbose_name': 'Ссылка на форму сдачи сочинений',
                'verbose_name_plural': 'Ссылки на формы сдачи сочинений',
            },
        ),
        migrations.CreateModel(
            name='EvaluationFormURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True, unique=True, verbose_name='Ссылка на форму')),
                ('evaluation_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_form_urls', to='api.essayevaluation', verbose_name='Работа для проверки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_form_urls', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('week_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_form_urls', to='api.weekid', verbose_name='Номер недели')),
            ],
            options={
                'verbose_name': 'Ссылка на форму сдачи проверок',
                'verbose_name_plural': 'Ссылки на формы сдачи проверок',
            },
        ),
        migrations.DeleteModel(
            name='FormURL',
        ),
    ]
