# Generated by Django 4.0.5 on 2022-07-06 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDistributionToEvaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий')),
                ('week_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_distribution', to='api.weekid', verbose_name='Идентификатор недели')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_distributions', to='api.essay', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Распределение работ',
                'verbose_name_plural': 'Распределения работ',
            },
        ),
    ]
