# Generated by Django 4.0.5 on 2022-07-07 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workdistributiontoevaluate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdistributiontoevaluate',
            name='week_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_distribution', to='api.weekid', verbose_name='Идентификатор недели'),
        ),
    ]
