# Generated by Django 4.0.5 on 2022-07-04 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_textkeys_textkey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textkey',
            options={'verbose_name': 'Ключ к тексту', 'verbose_name_plural': 'Ключи к тексту'},
        ),
        migrations.AlterField(
            model_name='textkey',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
