# Generated by Django 4.0.5 on 2022-07-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_text_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='week_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api.weekid', verbose_name='Идентификатор недели'),
        ),
    ]
