# Generated by Django 4.0.5 on 2022-07-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_textkey_options_alter_textkey_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essay',
            options={'verbose_name': 'Сочинение', 'verbose_name_plural': 'Сочинения'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тексты'},
        ),
    ]
