# Generated by Django 4.0.5 on 2022-07-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_evaluationformurl_evaluation_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essayevaluation',
            old_name='checker',
            new_name='evaluator',
        ),
    ]
