# Generated by Django 4.0.5 on 2022-07-04 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_text_week_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(editable=False, unique=True, verbose_name='Ссылка на форму')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_urls', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_urls', to='api.weekid', verbose_name='Номер недели')),
            ],
            options={
                'verbose_name': 'Ссылка на форму',
                'verbose_name_plural': 'Ссылки на формы',
            },
        ),
    ]
