# Generated by Django 4.0.5 on 2022-07-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_formurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formurl',
            name='url',
            field=models.URLField(unique=True, verbose_name='Ссылка на форму'),
        ),
    ]
