# Generated by Django 4.0.5 on 2022-07-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_essay_options_alter_text_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textkey',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='api.text', verbose_name='Текст'),
        ),
    ]
