# Generated by Django 4.0.5 on 2022-07-04 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_formurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formurl',
            name='url',
            field=models.URLField(null=True, unique=True, verbose_name='Ссылка на форму'),
        ),
        migrations.AlterField(
            model_name='formurl',
            name='week_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_urls', to='api.weekid', verbose_name='Номер недели'),
        ),
    ]
