# Generated by Django 4.0.5 on 2022-07-09 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_essaysentencereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaysentencereview',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
