# Generated by Django 4.0.5 on 2022-08-05 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_essaycriteria_k1_alter_essaycriteria_k10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsFormURL',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'url',
                    models.URLField(
                        null=True, unique=True, verbose_name='Ссылка на форму'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_form_urls',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
                (
                    'week_id',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_form_urls',
                        to='api.weekid',
                        verbose_name='Номер недели',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ссылка на форму просмотра результата',
                'verbose_name_plural': 'Ссылки на формы просмотра результатов',
            },
        ),
    ]
