# Generated by Django 4.0.5 on 2022-07-09 22:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_essaycriteria_k1_alter_essaycriteria_k10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaycriteria',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
