# Generated by Django 4.0.5 on 2022-08-10 00:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_resultsformurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essaysentencereview',
            options={
                'verbose_name': 'Предложение сочинения',
                'verbose_name_plural': 'Предложения сочинений',
            },
        ),
        migrations.CreateModel(
            name='RateEssayEvaluation',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'score',
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name='Рейтинг',
                    ),
                ),
                (
                    'evaluation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rates',
                        to='api.essayevaluation',
                        verbose_name='Проверка',
                    ),
                ),
                (
                    'rater',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rate_evaluations',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь, который оценил проверку',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Рейтинг проверки сочинений',
                'verbose_name_plural': 'Рейтинги проверок сочинений',
            },
        ),
    ]
