# Generated by Django 4.0.5 on 2022-08-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_rateessayevaluation_evaluation_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vkontakte_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
