name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          cp .env.example .env
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Build and test development mode
        run: |
          set -x
          make build_dev
          make up_dev
          make test_dev

  build_test_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env files
        run: |
          cp .env.example .env
          cp .env.db.example .env.db

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Build and test production mode
        run: |
          set -x
          make build_prod
          make up_prod
          make test_prod

  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Black lint module
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run Lint check
      run: |
        black . --config pyproject.toml --check


#  TODO: add mypy linting
